version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - bandit -r .
      - prospector
      - coverage run --source="." -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,setup.py