version: 0.2

phases:
  install:
    commands:
      - pip install prospector coverage bandit websockets
  pre_build:
    commands:
      - bandit -r .
      - prospector
      - coverage run --source="." -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,setup.py